DELETE  http://localhost:3001/api/blogs/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2FzQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2Nzg3OTI5MDd9.Q4U9JiyOk27nfdC-0SMuVt0CVcEtl0ap46UVF-K-Jxo
